name: "✨ Lint"

on:
  push:
    branches:
      - "master"
    paths:
      - "**.ts"
      - "**.tsx"
      - ".github/workflows/lint.yml"

jobs:
  deploy:
    name: "✨ Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.1.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install packages
        run: pnpm install

      - name: Lint
        run: pnpm lint
