CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"oidc_id_token" varchar NOT NULL,
	"id_token_exp" timestamp NOT NULL,
	"email" varchar NOT NULL,
	"picture_url" varchar NOT NULL,
	"name" varchar NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
